version: "3.8"

services:
  sonarqube:
    image: sonarqube:9.9.8-community
    container_name: sonarqube-custom
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_USERNAME=admin
      - SONAR_JDBC_PASSWORD=admin
      - SONAR_FORCE_AUTHENTICATION=true